name: CI | Unit

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - '**'

jobs:

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Lint files
        run: npm run lint

      - name: Run tests
        run: npm run test

  ci-unit:
    name: CI | Unit
    needs: run-tests
    runs-on: ubuntu-latest

    steps:

      # IMPORTANT NOTE
      #
      # You can not set a workflow to be status check. The job is. Hence the trickery...

      - name: Done
        run: echo "Done!"
